---
title: 오류
slug: ko/v2/guides/errors
---

## 소개

일부 오류 객체에는 `.cause` 속성이 설정되어 있습니다. 대부분의 경우 `unknown` 유형이며, 값은 추후 예고 없이 변경될 수 있습니다.

## 일반

### SurrealError

`SurrealError`는 이 SDK에서 명시적으로 발생시키는 오류 객체 대부분이 상속받는 기본 클래스입니다. 이 클래스는 JavaScript의 `Error` 클래스를 상속받습니다. 이 오류 객체가 단독으로 발생하는 경우는 거의 없으며, 기본적으로는 상속받는 특별한 의미를 가진 오류 객체가 발생합니다. `try-catch` 구문 등으로 잡은 오류가 이 SDK에서 명시적으로 발생시킨 오류인지 여부를 쉽게 분류하기 위해 사용하는 것을 권장합니다.

#### 속성

`.name: "SurrealError"`
:   오류 이름입니다.

`.message`
:   오류 메시지입니다.

`.stack`
:   스택 추적이 기록되어 있을 수 있습니다.

`.cause`
:   오류가 발생한 원인 또는 컨텍스트가 설정되어 있을 수 있습니다.

### SurrealTypeError

상속원: `SurrealError`

입력 값 또는 기타 검증에 실패한 경우 발생하는 오류입니다.

#### 속성

`.name: "SurrealTypeError"`
:   오류 이름입니다.

`.expected`
:   예상되는 데이터 형식입니다.

`.actual`
:   실제 값의 문자열 표현입니다.

#### 해결책

스택 추적을 따라 예상되는 데이터 형식이 입력되지 않는 원인을 찾습니다.

### SurrealValueError

상속원: `SurrealError`

입력 값 또는 기타 검증에 실패한 경우 발생하는 오류입니다.

#### 속성

`.name: "SurrealValueError"`
:   오류 이름입니다.

`.expected`
:   예상되는 데이터 형식입니다.

`.actual`
:   실제 값입니다.

#### 해결책

스택 추적을 따라 예상되는 데이터 형식이 입력되지 않는 원인을 찾습니다.

### SurrealAggregateError

상속원: `SurrealError`

여러 오류 또는 오류 메시지가 모인 오류입니다.

#### 속성

`.name: "SurrealAggregateError"`
:   오류 이름입니다.

`.cause: unknown[]`
:   배열의 각 요소에 오류 또는 오류 메시지 등이 포함되어 있습니다.

### CircularReferenceError

상속원: `SurrealError`

순환 참조를 감지한 경우 발생하는 오류입니다. 주로 JavaScript 값을 다른 형식으로 변환하는 과정에서 부모 객체와 동일한 객체가 감지된 경우 발생합니다.

#### 속성

`.name: "CircularReferenceError"`
:   오류 이름입니다.

`.reference: unknown`
:   순환 참조가 발생한 값입니다.

예를 들어 다음과 같은 경우에 이 오류가 발생합니다.

```ts
import { toSurql } from "@tai-kun/surrealdb/utils";

const a = {};
a.a = a;

console.log(a); // <ref *1> { a: [Circular *1] }

toSurql(a); // throws CircularReferenceError
```

#### 해결책

이 오류는 `toSurql` 함수 이외에도 일반적인 오류로 발생할 수 있습니다. 객체 내부에 해당 객체가 포함되어 있는지 신중하게 디버깅해야 합니다.

### NumberRangeError

상속원: `SurrealError`

숫자가 범위 밖의 값을 가진 경우 발생하는 오류입니다.

#### 속성

`.name: "NumberRangeError"`
:   오류 이름입니다.

`.range`
:   예상되는 범위입니다.

`.actual`
:   실제 값입니다.

`.integer`
:   `true`인 경우 정수를 예상합니다.

#### 해결책

스택 추적을 따라 예상되는 데이터 형식이 입력되지 않는 원인을 찾습니다.

### UnsupportedRuntimeError

상속원: `SurrealError`

지원되지 않는 런타임을 사용하고 있다고 판단된 경우 발생하는 오류입니다.

#### 속성

`.name: "UnsupportedRuntimeError"`
:   오류 이름입니다.

#### 해결책

해당 런타임을 사용하지 않거나, 폴리필을 사용하여 충분히 테스트해야 합니다.

### UnreachableError

상속원: `SurrealError`

도달할 수 없는 코드에 도달한 경우 발생하는 오류입니다. 이 오류가 발생한 경우, 아마도 이 SDK의 버그를 만난 것으로 생각됩니다.

#### 속성

`.name: "UnreachableError"`
:   오류 이름입니다.

#### 해결책

다음 URL에서 이 문제를 제기할 수 있습니다.

[https://github.com/tai-kun/surrealdb.js/issues](https://github.com/tai-kun/surrealdb.js/issues)

## 클라이언트

### CircularEngineReferenceError

상속원: `CircularReferenceError`

데이터베이스에 연결할 때, 엔진 간에 순환 참조가 발생한 경우 발생하는 오류입니다.

#### 속성

`.name: "CircularEngineReferenceError"`
:   오류 이름입니다.

`.reference: string`
:   순환 참조가 발생한 스키마 이름입니다.

`.seen: string[]`
:   순환 참조가 발생할 때까지 거쳐온 스키마 이름 목록입니다.

예를 들어 다음과 같은 경우에 이 오류가 발생합니다.

```ts
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: "https",
    https: "http",
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws CircularEngineReferenceError: Circular engine reference: http,https
```

위 예제에서는 https 프로토콜 엔진이 http에 설정된 엔진을 사용하도록 지정했지만, http 프로토콜 엔진은 다시 https에 설정된 엔진을 사용하려고 하기 때문에 순환 참조 오류가 발생합니다.

#### 해결책

문자열로 지정된 프로토콜 이름을 다른 프로토콜 이름의 값으로 설정하지 말고, 대신 엔진을 생성하는 구체적인 구현으로 대체합니다.

```ts del={6} ins={7-10}
import { initSurreal } from "@tai-kun/surrealdb";
import HttpEngine from "@tai-kun/surrealdb/http-engine";

const { Surreal } = initSurreal({
  engines: {
    http: "https",
    http: config => new HttpEngine({
      ...config,
      // fetch: <your custom fetch function>
    }),
    https: "http",
  },
  // ...
});
```

### EngineNotFoundError

상속원: `SurrealError`

엔진이 설정되지 않은 프로토콜로 연결하려고 할 때 발생하는 오류입니다.

#### 속성

`.name: "EngineNotFoundError"`
:   오류 이름입니다.

`.scheme: string`
:   연결 대상 프로토콜 이름입니다.

예를 들어 다음과 같은 경우에 이 오류가 발생합니다.

```ts
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws EngineNotFoundError: No https scheme engine found.
```

#### 해결책

연결 대상 엔드포인트의 프로토콜에서 엔진을 생성할 수 있는지 `engines` 속성을 확인합니다.

```ts ins={6}
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
    https: "http",
  },
  // ...
});
```

### ConnectionConflictError

상속원: `SurrealError`

클라이언트가 여러 엔드포인트에 동시에 연결하려고 할 때 발생하는 오류입니다.

#### 속성

`.name: "ConnectionConflictError"`
:   오류 이름입니다.

`.endpoint1: string`
:   이미 연결된 엔드포인트입니다.

`.endpoint2: string`
:   다른 엔드포인트입니다.

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("ws://localhost:8000");
await db.connect("ws://localhost:1129"); // throws ConnectionConflictError: An attempt was made to connect to ws://localhost:1129/rpc while ws://localhost:8000/rpc was already connected.
```

`.connect` 메서드는 전달된 URL의 경로가 `/rpc`로 끝나지 않으면, 해당 경로를 끝에 추가합니다. 따라서, 한쪽 엔드포인트의 URL 경로가 `/rpc`로 끝나는 경우에는, 외형과 달리 오류가 발생하지 않을 수 있습니다.

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:8000/rpc"); // OK!
```

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000/rpc");
await db.connect("http://localhost:8000"); // OK!
```

#### 해결책

`.connect` 메서드를 호출하기 전에 `.close` 메서드를 호출함으로써, 원하는 엔드포인트에 연결할 수 있습니다.

```ts ins={6}
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.close();
await db.connect("http://localhost:11298");
```

### MissingNamespaceError

상속원: `SurrealError`

데이터베이스를 선택하기 전에 네임스페이스가 선택되지 않은 경우 발생하는 오류입니다. 또는, 데이터베이스를 선택한 상태에서 네임스페이스를 선택하지 않은 상태로 유지하려고 할 때도 발생합니다.

#### 속성

`.name: "MissingNamespaceError"`
:   오류 이름입니다.

`.database: string`
:   데이터베이스 이름입니다.

예를 들어 다음과 같은 경우에 이 오류가 발생합니다.

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({
  database: "example",
}); // throws MissingNamespaceError: The namespace must be specified before the database.
```

#### 해결책

데이터베이스를 선택하는 경우 네임스페이스도 함께 선택합니다.

```ts ins={7}
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({
  namespace: "example",
  database: "example",
});
```

### RpcResponseError

상속원: `SurrealError`

RPC 응답이 오류를 나타내는 경우 발생하는 오류입니다. 연결된 프로토콜을 통한 통신 또는 응답 본문 디코딩에 문제는 없지만, SurrealDB에서 RPC 요청을 처리할 수 없음을 의미합니다.

#### 속성

`.name: "RpcResponseError"`
:   오류 이름입니다.

`.id?: string`
:   RPC 요청을 식별하는 ID입니다. ID는 항상 `<메서드 이름>_`으로 시작합니다.

`.code: number`
:   SurrealDB 문서에 명시되어 있지는 않지만, 아마도 JSON-RPC 오류 코드일 것입니다.

#### 해결책

다양한 원인이 있을 수 있지만, 이 SDK에서 지원하는 SurrealDB 버전과 RPC 요청을 처리하는 SurrealDB 버전이 다른 경우일 수 있습니다.

### QueryFailedError

상속원: `SurrealAggregateError`

쿼리가 실패한 경우 발생하는 오류입니다.

#### 속성

`.name: "QueryFailedError"`
:   오류 이름입니다.

`.cause: string[]`
:   오류 목록입니다.

예를 들어 다음과 같은 경우에 이 오류가 발생합니다.

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.query("OUTPUT 'Hello'"); // throws QueryFailedError: Query failed with 1 error(s)
```

#### 해결책

SurrelQL 문법이 올바른지 확인합니다.

### Closed

상속원: `SurrealError`

연결이 강제로 종료되었음을 나타내는 오류입니다.

#### 속성

`.name: "Closed"`
:   오류 이름입니다.

예를 들어 다음과 같은 경우에 이 오류를 얻습니다.

```ts
const db = new Surreal();

db.on("<event_name>", ({ signal }) => {
  return new Promise((resolve, reject) => {
    signal.addEventListener("abort", function() {
      console.error(this.reason); // Closed
      reject();
    })

    // ...
  });
});

await db.close({ force: true });
```

## 엔진

### EngineError

상속원: `SurrealError`

엔진에서 발생한 오류임을 나타냅니다. 이벤트 리스너를 통해 전송됩니다.

#### 속성

`.name: "EngineError"`
:   오류 이름입니다.

`.fatal: boolean | undefined`
:   이 오류가 치명적인지 여부를 나타냅니다.

### HttpEngineError

상속원: `EngineError`

HTTP 엔진에서 발생한 오류임을 나타냅니다. 현재는 정의만 되어 있고 사용되지 않습니다.

#### 속성

`.name: "HttpEngineError"`
:   오류 이름입니다.

### WebSocketEngineError

상속원: `EngineError`

WebSocket 엔진에서 발생한 오류임을 나타냅니다. RPC 요청을 식별하는 ID를 찾기 전에 응답 본문을 해석하는 데 실패하거나, WebSocket 객체에서 오류 이벤트를 수신했을 때, WebSocket 연결을 끊었을 때 등에 사용됩니다.

이 SDK에서는 `315x`를 사용자 지정 상태 코드로 사용합니다. 이 범위는 [IANA](https://www.iana.org/assignments/websocket/websocket.xml#close-code-number)에서 할당되지 않은 상태 코드입니다.

#### 속성

`.name: "WebSocketEngineError"`
:   오류 이름입니다.

`.code: number`
:   다음 상태 코드 중 하나입니다.
    - `1000`~`1015`: [MDN Reference](https://developer.mozilla.org/docs/Web/API/CloseEvent/code)
    - `3150`: `WebSocket`[^1] 인스턴스에서 "error" 이벤트를 수신했음을 나타냅니다.
    - `3151`: WebSocket 엔진이 등록하는 "open" 이벤트 핸들러 내에서 오류가 발생했음을 나타냅니다. 연결 중 상태에서 연결 상태로 전환하는 과정에서 `StateTransitionError`가 발생한 경우가 대부분입니다.
    - `3152`: WebSocket 엔진이 등록하는 "message" 이벤트 핸들러 내에서 오류가 발생했음을 나타냅니다. 다양한 원인이 있을 수 있지만, 이벤트 핸들러 내에서 `ServerResponseError` 또는 `RpcResponseError`가 발생했을 가능성이 높습니다. 잘못된 RPC 매개변수로 요청한 것이 원인일 수 있습니다. 이 경우, RPC 호출 원본 메서드는 (기본적으로) 5초 후에 타임아웃되어 실패합니다. SurrealDB v2.0.2 이전 버전에서는 더 광범위한 원인으로 타임아웃될 수 있습니다.
    - `3153`: ping 송수신에 실패했음을 나타냅니다. 일시적인 오류일 수 있지만, 계속해서 받는 경우 연결을 유지하지 못하고 있을 가능성이 있습니다.
    - `3154`: WebSocket 엔진이 등록하는 "close" 이벤트 핸들러 내에서 오류가 발생했음을 나타냅니다. 끊기 중 상태에서 끊긴 상태로 전환하는 과정에서 `StateTransitionError`가 발생한 경우가 대부분입니다.
:   참고로, 위에서 다음 상태 코드를 제외합니다. 이 SDK에서는 오류로 처리하지 않습니다.
    - `1000`: 정상적으로 끊겼습니다.
    - `1001`: 조기 끊김은 흔히 발생합니다.
    - `1004`: 예약됨.
    - `1005`: 예약됨.
    - `1006`: 예약됨.
    - `1015`: 예약됨.

^1: `WebSocket`은 런타임에서 전역 변수에 정의된 클래스이거나 `ws`의 클래스일 수 있습니다.

#### 해결책

`1002`,`1003`,`1007`...`1011`,`1014`,`3150`,`3151`,`3154`
:   이 상태 코드에서 자동으로 복구하는 방법은 아마 없을 것입니다. 런타임 또는 SurrealDB 설정, 하드 코딩된 구현을 수정해야 합니다.

`3152`
:   메서드에 전달한 인수 (즉, RPC 요청 내용)가 올바른지 확인합니다.

`1012`,`1013`,`3153`
:   실험적인 기능인 [`autoReconnect()`](/v2/experimental/auto-reconnect)을 사용하여 자동으로 복구할 수 있을 수 있습니다.

### StateTransitionError

상속원: `SurrealAggregateError`

상태 전환 중에 이벤트 리스너 실행에 실패한 경우 발생하는 오류입니다.

#### 속성

`.name: "StateTransitionError"`
:   오류 이름입니다.

`.from: string`
:   상태 전환 시작 시 상태입니다.

`.to: string`
:   전환 대상 상태입니다.

`.fallback: string`
:   상태 전환에 실패한 경우 대체 전환 대상입니다. `.to`와 동일한 값이면 강제로 전환되었음을 의미합니다.

예를 들어 다음과 같은 경우에 이 오류가 발생합니다.

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

db.on("connecting", () => {
  throw new Error("Don't let me connect !!!")
});

await db.connect("http://localhost:8000"); // throws ...
// StateTransitionError: The transition from `3` to `0` failed, falling back to `3`.
//     at <stack trace ...> {
//   cause: [
//     Error: Don't let me connect !!!
//         at <stack trace ...>
//   ],
//   from: 3,
//   to: 0,
//   fallback: 3
// }
```

### ConnectionUnavailableError

상속원: `SurrealError`

연결되지 않은 상태에서 RPC 요청을 전송하려고 할 때 발생하는 오류입니다.

#### 속성

`.name: "ConnectionUnavailableError"`
:   오류 이름입니다.

### ServerResponseError

상속원: `SurrealError`

응답을 PRC 응답으로 해석할 수 없는 경우 발생하는 오류입니다. `RpcResponseError`와는 다릅니다.

#### 속성

`.name: "ServerResponseError"`
:   오류 이름입니다.

#### 해결책

일반적으로 이 오류가 발생하는 경우는 없어야 하지만, 만약 발생한다면, 이 SDK에서 지원하는 SurrealDB 버전과 RPC 요청을 처리하는 SurrealDB 버전이 다른 경우일 수 있습니다.

## CBOR

### CborError

상속원: `SurrealError`

`@tai-kun/surrealdb/cbor`가 명시적으로 발생시키는, CBOR와 관련된 모든 오류가 상속받는 클래스입니다. 이 클래스가 직접 발생하지 않습니다.

#### 속성

`.name: "CborError"`
:   오류 이름입니다.

### CborWellFormednessError

상속원: `CborError`

#### 속성

`@tai-kun/surrealdb/cbor`가 명시적으로 발생시키는, CBOR 디코딩과 관련된 모든 오류가 상속받는 클래스입니다. 이 클래스가 직접 발생하지 않습니다.

RFC8949의 부록 F에 있는 "Well-Formedness Errors and Examples"를 참조합니다.

`.name: "CborWellFormednessError"`
:   오류 이름입니다.

### CborTooMuchDataError

상속원: `CborWellFormednessError`

소비되지 않은 입력 바이트가 남아 있음을 나타냅니다.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.2)

#### 속성

`.name: "CborTooMuchDataError"`
:   오류 이름입니다.

#### 해결책

디코딩 대상 바이트 배열이 올바른 CBOR 형식인지 확인합니다.

### CborTooLittleDataError

상속원: `CborWellFormednessError`

입력 바이트가 불완전함을 나타냅니다.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.4)

#### 속성

`.name: "CborTooLittleDataError"`
:   오류 이름입니다.

#### 해결책

디코딩 대상 바이트 배열이 올바른 CBOR 형식인지 확인합니다.

### CborSyntaxError

상속원: `CborWellFormednessError`

입력 바이트가 CBOR 인코딩 형식과 일치하지 않음을 나타냅니다.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.6)

#### 속성

`.name: "CborSyntaxError"`
:   오류 이름입니다.

#### 해결책

디코딩 대상 바이트 배열이 올바른 CBOR 형식인지 확인합니다.

### CborMaxDepthReachedError

상속원: `CborError`

CBOR 인코딩 또는 디코딩 시 JavaScript 객체의 깊이가 최대 값에 도달한 경우 발생하는 오류입니다. 객체 또는 배열에 들어갈 때마다 깊이가 1씩 증가합니다.

#### 속성

`.name: "CborMaxDepthReachedError"`
:   오류 이름입니다.

`.maxDepth: number`
:   최대 깊이입니다.

#### 해결책

옵션인 `.maxDepth`의 상한을 완화하거나, 객체의 중첩이 얕아지도록 데이터 구조를 재검토합니다.

```ts
import CborFormatter from "@tai-kun/surrealdb/cbor-formatter";

const cborFormatter = new CborFormatter({
  encode: {
    maxDepth: 1024,
  },
  decode: {
    maxDepth: 1024,
  },
  // ...
})
```

### CborUnsafeMapKeyError

상속원: `CborError`

CBOR 인코딩 또는 디코딩 시 안전하지 않은 맵 키가 발견되면 발생하는 오류입니다.

#### 속성

`.name: "CborUnsafeMapKeyError"`
:   오류 이름입니다.

`.key: unknown`
:   안전하지 않다고 판단된 맵 키입니다.

## JSON

### JsonError

상속원: `SurrealError`

`@tai-kun/surrealdb/json`가 명시적으로 발생시키는, JSON-formatter입니다.

#### 속성

`.name: "JsonError"`
:   오류 이름입니다.

### JsonUnsafeMapKeyError

상속원: `JsonError`

JSON 디코딩 시 안전하지 않은 맵 키가 발견되면 발생하는 오류입니다.

#### 속성

`.name: "JsonUnsafeMapKeyError"`
:   오류 이름입니다.

`.key: unknown`
:   안전하지 않다고 판단된 맵 키입니다.
