---
title: 错误
slug: zh-CN/v1/reference/errors
---

## SurrealError

`SurrealError` 是该 SDK 显式抛出的绝大多数错误对象的基类。该类继承自 JavaScript 的 `Error` 类。很少单独抛出该错误对象，通常会抛出具有特殊含义的继承类错误对象。推荐在 `try-catch` 语句中捕获这些错误，以便轻松地将它们分类为 SDK 显式抛出的错误。

`.name: "SurrealError"`
:   错误名称。

`.message`
:   错误消息。

`.stack`
:   可能会记录堆栈跟踪。

`.cause`
:   可能会设置发生错误的原因或上下文。

## SurrealTypeError

继承自: `SurrealError`

当输入值或其他验证失败时抛出此错误。

`.name: "SurrealTypeError"`
:   错误名称。

`.expected`
:   期望的数据类型。

`.actual`
:   实际值的字符串表示形式。

## SurrealAggregateError

继承自: `SurrealError`

这是一个包含多个错误或错误消息的错误。

`.name: "SurrealAggregateError"`
:   错误名称。

`.cause: unknown[]`
:   数组的每个元素都包含错误或错误消息等。

## CircularReferenceError

继承自: `SurrealError`

当检测到循环引用时抛出此错误。主要在将 JavaScript 值转换为其他格式的过程中，如果检测到父对象与相同对象，则会抛出此错误。

`.name: "CircularReferenceError"`
:   错误名称。

例如，在以下情况下会抛出此错误：

```ts
import { toSurql } from "@tai-kun/surrealdb/utils";

const a = {};
a.a = a;

console.log(a); // <ref *1> { a: [Circular *1] }

toSurql(a); // throws CircularReferenceError
```

## NumberRangeError

继承自: `SurrealError`

当数字超出范围时抛出此错误。

`.name: "NumberRangeError"`
:   错误名称。

`.range`
:   期望的范围。

`.actual`
:   实际值。

`.integer`
:   如果为 `true`，则期望整数。

## UnsupportedRuntimeError

继承自: `SurrealError`

当检测到使用不支持的运行时时抛出此错误。

`.name: "UnsupportedRuntimeError"`
:   错误名称。

## UnreachableError

继承自: `SurrealError`

当到达不可到达的代码时抛出此错误。如果抛出此错误，则可能遇到了 SDK 的错误。

`.name: "UnreachableError"`
:   错误名称。

## CircularEngineReferenceError

继承自: `CircularReferenceError`

当在连接数据库时发生引擎之间的循环引用时抛出此错误。

`.name: "CircularEngineReferenceError"`
:   错误名称。

`.seen: string[]`
:   发生循环引用之前经过的协议名称列表。

例如，在以下情况下会抛出此错误：

```ts
const { Surreal } = initSurreal({
  engines: {
    http: "https",
    https: "http",
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws CircularEngineReferenceError: Circular engine reference: http,https
```

上面的例子中，https 协议的引擎配置使用 http 引擎，但 http 协议的引擎又尝试使用 https 引擎，从而导致循环引用错误。

## EngineNotFoundError

继承自: `SurrealError`

当尝试使用未配置引擎的协议连接时抛出此错误。

`.name: "EngineNotFoundError"`
:   错误名称。

`.protocol: string`
:   连接到的协议名称。

例如，在以下情况下会抛出此错误：

```ts
const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws EngineNotFoundError: No https protocol engine found.
```

## ConnectionConflictError

继承自: `SurrealError`

当客户端尝试同时连接到多个端点时抛出此错误。

`.name: "ConnectionConflictError"`
:   错误名称。

`.endpoint1: string`
:   一个端点。

`.endpoint2: string`
:   另一个端点。

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:11298"); // throws ConnectionConflictError: Connection conflict between http://localhost:8000/rpc and http://localhost:11298/rpc.
```

`.connect` 方法会将传入的 URL 的路径添加 `/rpc` 作为后缀（如果路径不是以 `/rpc` 结尾）。因此，如果其中一个端点的 URL 路径以 `/rpc` 结尾，则可能不会抛出错误，尽管看起来它应该抛出：

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:8000/rpc"); // OK!
```

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000/rpc");
await db.connect("http://localhost:8000"); // OK!
```

## NamespaceConflictError

继承自: `SurrealError`

当 SDK 尝试同时切换到多个不同的命名空间时抛出此错误。

`.name: "NamespaceConflictError"`
:   错误名称。

`.namespace1: string`
:   一个命名空间。

`.namespace2: string`
:   另一个命名空间。

例如，在以下情况下会抛出此错误：

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.signin({ user: "root", pass: "root" });
await Promise.all([
  db.use({ namespace: "foo" }),
  db.use({ namespace: "bar" }),
]);
```

## DatabaseConflictError

继承自: `SurrealError`

当 SDK 尝试同时切换到多个不同的数据库时抛出此错误。

`.name: "DatabaseConflictError"`
:   错误名称。

`.database1: string`
:   一个数据库。

`.database2: string`
:   另一个数据库。

例如，在以下情况下会抛出此错误：

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.signin({ user: "root", pass: "root" });
await Promise.all([
  db.use({ namespace: "baz" database: "foo" }),
  db.use({ namespace: "baz" database: "bar" }),
]);
```

## MissingNamespaceError

继承自: `SurrealError`

当在选择数据库之前没有选择命名空间时抛出此错误。或者，即使选择数据库后，也尝试将命名空间设置为未选择状态时抛出此错误。

`.name: "MissingNamespaceError"`
:   错误名称。

`.database: string`
:   数据库名称。

例如，在以下情况下会抛出此错误：

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({ database: "example" }); // throws MissingNamespaceError: The namespace must be specified before the database.
```

## RpcResponseError

继承自: `SurrealError`

当 RPC 响应指示错误时抛出此错误。连接到的协议的通信或响应主体的解码没有问题，但这意味着 SurrealDB 无法处理 RPC 请求。

`.name: "RpcResponseError"`
:   错误名称。

`.id?: string`
:   用于识别 RPC 请求的 ID。ID 始终以 `<方法名>_` 开头。

`.code: number`
:   SurrealDB 文档中没有明确说明，但可能是 JSON-RPC 的错误代码。

## QueryFailedError

继承自: `SurrealAggregateError`

当查询失败时抛出此错误。

`.name: "QueryFailedError"`
:   错误名称。

`.cause: string[]`
:   错误列表。

例如，在以下情况下会抛出此错误：

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.query("OUTPUT 'Hello'"); // throws QueryFailedError: Query failed with 1 error(s)
```

## Disconnected

继承自: `SurrealError`

此错误表示连接已强制终止。

`.name: "Disconnected"`
:   错误名称。

例如，在以下情况下会得到此错误：

```ts
const db = new Surreal();

db.on("<event_name>", ({ signal }) => {
  return new Promise((resolve, reject) => {
    signal.addEventListener("abort", function() {
      console.error(this.reason); // Disconnected
      reject();
    })

    // ...
  });
});

await db.disconnect({ force: true });
```

## EngineError

继承自: `SurrealError`

此错误表示该错误是由引擎引起的。通过事件监听器发送。

`.name: "EngineError"`
:   错误名称。

`.fatal: boolean | undefined`
:   指示该错误是否致命。

## HttpEngineError

继承自: `EngineError`

此错误表示该错误是由 HTTP 引擎引起的。目前只有定义，没有使用。

`.name: "HttpEngineError"`
:   错误名称。

## WebSocketEngineError

继承自: `EngineError`

此错误表示该错误是由 WebSocket 引擎引起的。当在找到识别 RPC 请求的 ID 之前解析响应主体失败时，或从 WebSocket 对象接收错误事件时，或断开 WebSocket 连接时使用。

`.name: "WebSocketEngineError"`
:   错误名称。

`.code: number`
:   以下状态代码之一：
    - `1000`~`1015`: [MDN 参考](https://developer.mozilla.org/docs/Web/API/CloseEvent/code)
    - `3150`: 表示从 `WebSocket`[^1] 实例接收到 "error" 事件。
    - `3151`: 表示 WebSocket 引擎在注册的 "open" 事件处理程序中发生错误。这通常是 `StateTransitionError` 在连接状态转换过程中发生的错误。
    - `3152`: 表示 WebSocket 引擎在注册的 "message" 事件处理程序中发生错误。可能有多种原因，但很可能是事件处理程序中抛出了 `ResponseError` 或 `RpcResponseError`。追溯到根源，可能是请求了语法错误的 SurrealQL 自定义查询或使用无效的 RPC 参数进行了请求。在这种情况下，RPC 的调用方方法（默认情况下）将在 5 秒后超时并失败。
    - `3153`: 表示 ping 的发送或接收失败。这可能是一个暂时性的错误，但如果持续收到此错误，则可能无法保持连接。
    - `3154`: 表示 WebSocket 引擎在注册的 "close" 事件处理程序中发生错误。这通常是 `StateTransitionError` 在断开连接状态转换过程中发生的错误。
:   此外，不包括以下状态代码。该 SDK 不将其视为错误：
    - `1000`: 正常断开连接。
    - `1001`: 提前断开连接很常见。
    - `1004`: 保留。
    - `1005`: 保留。
    - `1006`: 保留。
    - `1015`: 保留。

^1: `WebSocket` 可以是运行时在全局变量中定义的类，也可以是 `ws` SDK 的类。

## StateTransitionError

继承自: `SurrealAggregateError`

当状态转换期间执行事件监听器失败时抛出此错误。

`.name: "StateTransitionError"`
:   错误名称。

`.from: number`
:   开始状态转换时的状态。

`.to: number`
:   目标状态。

`.fallback: number`
:   状态转换失败时的替代目标。如果与 `.to` 相同，则表示强制转换成功。

例如，在以下情况下会抛出此错误：

```ts
import { Surreal } from "@tai-kun/surrealdb";
import { CONNECTING } from "@tai-kun/surrealdb/engine";

await using db = new Surreal();

db.on(CONNECTING, () => {
  throw new Error("Don't let me connect !!!")
});

await db.connect("http://localhost:8000"); // throws ...
// StateTransitionError: The transition from `3` to `0` failed, falling back to `3`.
//     at <stack trace ...> {
//   cause: [
//     Error: Don't let me connect !!!
//         at <stack trace ...>
//   ],
//   from: 3,
//   to: 0,
//   fallback: 3
// }
```

## ConnectionUnavailableError

继承自: `SurrealError`

当尝试在未连接状态下发送 RPC 请求时抛出此错误。

`.name: "ConnectionUnavailableError"`
:   错误名称。

## ResponseError

继承自: `SurrealError`

当无法将响应解析为 PRC 响应时抛出此错误。与 `RpcResponseError` 不同。

`.name: "ResponseError"`
:   错误名称。

## CborError

继承自: `SurrealError`

这是 `@tai-kun/surrealdb/cbor` 显式抛出的所有与 CBOR 相关的错误的基类。它不会直接被抛出。

`.name: "CborError"`
:   错误名称。

## CborWellFormednessError

继承自: `CborError`

这是 `@tai-kun/surrealdb/cbor` 显式抛出的所有与 CBOR 解码相关的错误的基类。它不会直接被抛出。

请参阅 RFC8949 附录 F 中的 “[Well-Formedness Errors and Examples](https://datatracker.ietf.org/doc/html/rfc8949#name-well-formedness-errors-and-)”。

`.name: "CborWellFormednessError"`
:   错误名称。

## CborTooMuchDataError

继承自: `CborWellFormednessError`

这表示存在未被消耗的输入字节。

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.2)

`.name: "CborTooMuchDataError"`
:   错误名称。

## CborTooLittleDataError

继承自: `CborWellFormednessError`

这表示输入字节不完整。

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.4)

`.name: "CborTooLittleDataError"`
:   错误名称。

## CborSyntaxError

继承自: `CborWellFormednessError`

这表示输入字节与 CBOR 的编码格式不匹配。

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.6)

`.name: "CborSyntaxError"`
:   错误名称。

## CborMaxDepthReachedError

继承自: `CborError`

当 CBOR 编码或解码时 JavaScript 对象的深度达到最大值时抛出此错误。每进入一个对象或数组，深度就会增加 1。

`.name: "CborMaxDepthReachedError"`
:   错误名称。

`.maxDepth: number`
:   最大深度。

## CborUnsafeMapKeyError

继承自: `CborError`

当 CBOR 编码或解码时遇到不安全的映射键时抛出此错误。

`.name: "CborUnsafeMapKeyError"`
:   错误名称。

`.key: unknown`
:   被判定为不安全的映射键。
