---
title: Errors
slug: en/v2/guides/errors
---

## Introduction

Some error objects may have a `.cause` property. In most cases, this is of type `unknown`, and its value is subject to change without notice. 

## General

### SurrealError

`SurrealError` is the base class that most error objects thrown explicitly by this SDK inherit from. This class inherits from JavaScript's `Error` class. This error object is rarely thrown on its own.  Instead, inherited error objects with specific meanings are typically thrown.  It is recommended to use this error object as a way to easily categorize errors caught in `try-catch` blocks as errors explicitly thrown by this SDK.

#### Properties

`.name: "SurrealError"`
:   The name of the error.

`.message`
:   The error message.

`.stack`
:   A stack trace may be recorded.

`.cause`
:   The cause or context of the error may be set.

### SurrealTypeError

Inherits from: `SurrealError`

This error is thrown when there is a failure in input value or other validations.

#### Properties

`.name: "SurrealTypeError"`
:   The name of the error.

`.expected`
:   The expected data format.

`.actual`
:   The string representation of the actual value.

#### Solution

Trace the stack to find the source of the unexpected data format.

### SurrealValueError

Inherits from: `SurrealError`

This error is thrown when there is a failure in input value or other validations.

#### Properties

`.name: "SurrealValueError"`
:   The name of the error.

`.expected`
:   The expected data format.

`.actual`
:   The actual value.

#### Solution

Trace the stack to find the source of the unexpected data format.

### SurrealAggregateError

Inherits from: `SurrealError`

This error represents an aggregation of multiple errors or error messages.

#### Properties

`.name: "SurrealAggregateError"`
:   The name of the error.

`.cause: unknown[]`
:   Each element of the array contains errors, error messages, or other relevant information.

### CircularReferenceError

Inherits from: `SurrealError`

This error is thrown when a circular reference is detected, primarily during the process of converting JavaScript values into another format. This typically occurs when a parent object is found to contain the same object within itself.

#### Properties

`.name: "CircularReferenceError"`
:   The name of the error.

`.reference: unknown`
:   The value where the circular reference occurred.

For example, this error is thrown in cases like:

```ts
import { toSurql } from "@tai-kun/surrealdb/utils";

const a = {};
a.a = a;

console.log(a); // <ref *1> { a: [Circular *1] }

toSurql(a); // throws CircularReferenceError
```

#### Solution

This error can occur beyond the `toSurql` function. It is a general error that requires careful debugging to identify and resolve circular references within objects.

### NumberRangeError

Inherits from: `SurrealError`

This error is thrown when a number falls outside the expected range.

#### Properties

`.name: "NumberRangeError"`
:   The name of the error.

`.range`
:   The expected range.

`.actual`
:   The actual value.

`.integer`
:   If `true`, an integer is expected.

#### Solution

Trace the stack to find the source of the unexpected data format.

### UnsupportedRuntimeError

Inherits from: `SurrealError`

This error is thrown when an unsupported runtime is detected.

#### Properties

`.name: "UnsupportedRuntimeError"`
:   The name of the error.

#### Solution

Either avoid using that runtime or use a polyfill and thoroughly test.

### UnreachableError

Inherits from: `SurrealError`

This error is thrown when unreachable code is reached.  It is likely that you have encountered a bug in this SDK if you encounter this error.

#### Properties

`.name: "UnreachableError"`
:   The name of the error.

#### Solution

You can raise this issue at the following URL:

[https://github.com/tai-kun/surrealdb.js/issues](https://github.com/tai-kun/surrealdb.js/issues)

## Client

### CircularEngineReferenceError

Inherits from: `CircularReferenceError`

This error is thrown when a circular reference is detected among engines during database connection.

#### Properties

`.name: "CircularEngineReferenceError"`
:   The name of the error.

`.reference: string`
:   The scheme name where the circular reference occurred.

`.seen: string[]`
:   List of scheme names traversed before the circular reference was detected.

For example, this error is thrown in cases like:

```ts
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: "https",
    https: "http",
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws CircularEngineReferenceError: Circular engine reference: http,https
```

In the above example, the https protocol engine tries to use the engine configured for the http protocol, but the http protocol engine attempts to use the engine configured for the https protocol, leading to a circular reference.

#### Solution

Instead of assigning a string that is a protocol name to a value that is another protocol name, replace it with a specific implementation that creates an engine:

```ts del={6} ins={7-10}
import { initSurreal } from "@tai-kun/surrealdb";
import HttpEngine from "@tai-kun/surrealdb/engines/http";

const { Surreal } = initSurreal({
  engines: {
    http: "https",
    http: config => new HttpEngine({
      ...config,
      // fetch: <your custom fetch function>
    }),
    https: "http",
  },
  // ...
});
```

### EngineNotFoundError

Inherits from: `SurrealError`

This error is thrown when an attempt is made to connect with a protocol for which no engine is configured.

#### Properties

`.name: "EngineNotFoundError"`
:   The name of the error.

`.scheme: string`
:   The protocol name of the target endpoint.

For example, this error is thrown in cases like:

```ts
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws EngineNotFoundError: No https scheme engine found.
```

#### Solution

Check if the protocol of the target endpoint has an engine configured in the `engines` property.

```ts ins={6}
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
    https: "http",
  },
  // ...
});
```

### ConnectionConflictError

Inherits from: `SurrealError`

This error is thrown when the client attempts to connect to multiple endpoints simultaneously.

#### Properties

`.name: "ConnectionConflictError"`
:   The name of the error.

`.endpoint1: string`
:   The endpoint that is already connected.

`.endpoint2: string`
:   The other endpoint.

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("ws://localhost:8000");
await db.connect("ws://localhost:1129"); // throws ConnectionConflictError: An attempt was made to connect to ws://localhost:1129/rpc while ws://localhost:8000/rpc was already connected.
```

The `.connect` method appends `/rpc` to the end of the provided URL path if it does not end with it. Therefore, it is possible for an error not to occur, contrary to appearances, if the URL path of one of the endpoints ends with `/rpc`:

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:8000/rpc"); // OK!
```

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000/rpc");
await db.connect("http://localhost:8000"); // OK!
```

#### Solution

You can connect to any endpoint by calling the `.close` method before calling the `.connect` method.

```ts ins={6}
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.close();
await db.connect("http://localhost:11298");
```

### MissingNamespaceError

Inherits from: `SurrealError`

This error is thrown when a namespace is not selected before selecting a database, or when attempting to leave the namespace unselected while a database is selected.

#### Properties

`.name: "MissingNamespaceError"`
:   The name of the error.

`.database: string`
:   The database name.

For example, this error is thrown in cases like:

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({
  database: "example",
}); // throws MissingNamespaceError: The namespace must be specified before the database.
```

#### Solution

Select the namespace as well when selecting the database.

```ts ins={7}
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({
  namespace: "example",
  database: "example",
});
```

### RpcResponseError

Inherits from: `SurrealError`

This error is thrown when the RPC response indicates an error. This means that there are no issues with the communication or the decoding of the response body based on the protocol used to connect, but SurrealDB cannot process the RPC request.

#### Properties

`.name: "RpcResponseError"`
:   The name of the error.

`.id?: string`
:   The ID that identifies the RPC request. The ID always starts with `<method name>_`.

`.code: number`
:   This is likely the JSON-RPC error code, though it is not explicitly documented in the SurrealDB documentation.

#### Solution

The cause of this error can vary. One possible reason is that the version of SurrealDB supported by this SDK differs from the version of SurrealDB that processes the RPC request.

### QueryFailedError

Inherits from: `SurrealAggregateError`

This error is thrown when a query fails.

#### Properties

`.name: "QueryFailedError"`
:   The name of the error.

`.cause: string[]`
:   A list of errors.

For example, this error is thrown in cases like:

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.query("OUTPUT 'Hello'"); // throws QueryFailedError: Query failed with 1 error(s)
```

#### Solution

Check the correctness of the SurrelQL syntax.

### Closed

Inherits from: `SurrealError`

This error indicates that the connection has been forcibly terminated.

#### Properties

`.name: "Closed"`
:   The name of the error.

For example, you will get this error in the following case:

```ts
const db = new Surreal();

db.on("<event_name>", ({ signal }) => {
  return new Promise((resolve, reject) => {
    signal.addEventListener("abort", function() {
      console.error(this.reason); // Closed
      reject();
    })

    // ...
  });
});

await db.close({ force: true });
```

## Engine

### EngineError

Inherits from: `SurrealError`

This indicates that an error originated from the engine. It is emitted through event listeners.

#### Properties

`.name: "EngineError"`
:   The name of the error.

`.fatal: boolean | undefined`
:   Indicates whether this error is fatal.

### HttpEngineError

Inherits from: `EngineError`

This indicates that an error originated from the HTTP engine. Currently, this is only defined and not used.

#### Properties

`.name: "HttpEngineError"`
:   The name of the error.

### WebSocketEngineError

Inherits from: `EngineError`

This indicates that an error originated from the WebSocket engine. This is used when there is an issue with parsing the response body before identifying the RPC request ID, when receiving an error event from the WebSocket object, or when the WebSocket connection is closed.

This SDK uses `315x` as custom status codes. This range is unassigned for status codes in [IANA](https://www.iana.org/assignments/websocket/websocket.xml#close-code-number).

#### Properties

`.name: "WebSocketEngineError"`
:   The name of the error.

`.code: number`
:   One of the following status codes:
    - `1000`~`1015`: [MDN Reference](https://developer.mozilla.org/docs/Web/API/CloseEvent/code)
    - `3150`: Indicates an "error" event was received from the `WebSocket`[^1] instance.
    - `3151`: Indicates an error occurred within the "open" event handler registered by the WebSocket engine. This is most likely a `StateTransitionError` during the transition from the connecting state to the connected state.
    - `3152`: Indicates an error occurred within the "message" event handler registered by the WebSocket engine. While there can be various causes, it is likely that a `ServerResponseError` or `RpcResponseError` was thrown inside the event handler. This could be caused by requesting with invalid RPC parameters. In this case, the method calling the RPC (by default) times out after 5 seconds and fails. In versions of SurrealDB prior to v2.0.2, timeouts could occur for more broad reasons.
    - `3153`: Indicates a failure in sending or receiving a ping. While this could be a temporary error, if it continues, it could mean that the connection is not being maintained.
    - `3154`: Indicates an error occurred within the "close" event handler registered by the WebSocket engine. This is most likely a `StateTransitionError` during the transition from the closing state to the closed state.
:   Note that the following status codes are excluded from the above. They are not treated as errors in this SDK.
    - `1000`: Indicates a normal closure.
    - `1001`: Early closure is common.
    - `1004`: Reserved.
    - `1005`: Reserved.
    - `1006`: Reserved.
    - `1015`: Reserved.

^1: `WebSocket` can be a class defined as a global variable by the runtime or a class from `ws`.

#### Solution

`1002`,`1003`,`1007`...`1011`,`1014`,`3150`,`3151`,`3154`
:   There is likely no automatic way to recover from these status codes. You need to modify the runtime, SurrealDB settings, or hard-coded implementations.

`3152`
:   Verify the arguments passed to the method (i.e., the content of the RPC request).

`1012`,`1013`,`3153`
:   You may be able to automatically recover using the experimental feature [`autoReconnect()`](/v2/experimental/auto-reconnect).

### StateTransitionError

Inherits from: `SurrealAggregateError`

This error is thrown when the execution of the event listener fails during a state transition.

#### Properties

`.name: "StateTransitionError"`
:   The name of the error.

`.from: string`
:   The state at the start of the transition.

`.to: string`
:   The target state of the transition.

`.fallback: string`
:   The alternative target state in case the state transition fails. If the value is the same as `.to`, it means that the transition was forced.

For example, this error is thrown in cases like:

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

db.on("connecting", () => {
  throw new Error("Don't let me connect !!!")
});

await db.connect("http://localhost:8000"); // throws ...
// StateTransitionError: The transition from `3` to `0` failed, falling back to `3`.
//     at <stack trace ...> {
//   cause: [
//     Error: Don't let me connect !!!
//         at <stack trace ...>
//   ],
//   from: 3,
//   to: 0,
//   fallback: 3
// }
```

### ConnectionUnavailableError

Inherits from: `SurrealError`

This error is thrown when an attempt is made to send an RPC request while not connected.

#### Properties

`.name: "ConnectionUnavailableError"`
:   The name of the error.

### ServerResponseError

Inherits from: `SurrealError`

This error is thrown when the response cannot be parsed as a PRC response. This is different from `RpcResponseError`.

#### Properties

`.name: "ServerResponseError"`
:   The name of the error.

#### Solution

Typically, this error should not be thrown. If it is thrown, the version of SurrealDB supported by this SDK may differ from the version of SurrealDB processing the RPC request.

## CBOR

### CborError

Inherits from: `SurrealError`

This is the class that all errors related to CBOR explicitly thrown by `@tai-kun/surrealdb/cbor` inherit from. It is never thrown directly.

#### Properties

`.name: "CborError"`
:   The name of the error.

### CborWellFormednessError

Inherits from: `CborError`

#### Properties

This is the class that all errors related to CBOR decoding explicitly thrown by `@tai-kun/surrealdb/cbor` inherit from. It is never thrown directly.

Refer to the "Well-Formedness Errors and Examples" in Appendix F of RFC8949 ([https://datatracker.ietf.org/doc/html/rfc8949#name-well-formedness-errors-and-](https://datatracker.ietf.org/doc/html/rfc8949#name-well-formedness-errors-and-)).

`.name: "CborWellFormednessError"`
:   The name of the error.

### CborTooMuchDataError

Inherits from: `CborWellFormednessError`

This indicates that there are remaining input bytes that were not consumed.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.2)

#### Properties

`.name: "CborTooMuchDataError"`
:   The name of the error.

#### Solution

Verify that the byte array being decoded is in the correct CBOR format.

### CborTooLittleDataError

Inherits from: `CborWellFormednessError`

This indicates that the input bytes are incomplete.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.4)

#### Properties

`.name: "CborTooLittleDataError"`
:   The name of the error.

#### Solution

Verify that the byte array being decoded is in the correct CBOR format.

### CborSyntaxError

Inherits from: `CborWellFormednessError`

This indicates that the input bytes do not match the CBOR encoding format.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.6)

#### Properties

`.name: "CborSyntaxError"`
:   The name of the error.

#### Solution

Verify that the byte array being decoded is in the correct CBOR format.

### CborMaxDepthReachedError

Inherits from: `CborError`

This error is thrown when the maximum depth of the JavaScript object is reached during CBOR encoding or decoding. The depth increases by 1 for each object or array entered.

#### Properties

`.name: "CborMaxDepthReachedError"`
:   The name of the error.

`.maxDepth: number`
:   The maximum depth.

#### Solution

Either loosen the upper limit of the optional `.maxDepth` or restructure the data so that the nesting of objects is shallower.

```ts
import CborFormatter from "@tai-kun/surrealdb/formatters/cbor";

const cborFormatter = new CborFormatter({
  encode: {
    maxDepth: 1024,
  },
  decode: {
    maxDepth: 1024,
  },
  // ...
})
```

### CborUnsafeMapKeyError

Inherits from: `CborError`

This error is thrown when an unsafe map key is found during CBOR encoding or decoding.

#### Properties

`.name: "CborUnsafeMapKeyError"`
:   The name of the error.

`.key: unknown`
:   The map key that is deemed unsafe.

## JSON

### JsonError

Inherits from: `SurrealError`

This is the class that all errors related to JSON explicitly thrown by `@tai-kun/surrealdb/formatters/json` inherit from. It is never thrown directly.

#### Properties

`.name: "JsonError"`
:   The name of the error.

### JsonUnsafeMapKeyError

Inherits from: `JsonError`

This error is thrown when an unsafe map key is found during JSON decoding.

#### Properties

`.name: "JsonUnsafeMapKeyError"`
:   The name of the error.

`.key: unknown`
:   The map key that is deemed unsafe.
