---
title: Errors
slug: en/v2/guides/errors
---

## Introduction

Some error objects may have a `.cause` property. This is usually of type `unknown`, and its value is subject to change without notice.

## General

### SurrealError

`SurrealError` is the base class that most of the error objects explicitly thrown by this SDK inherit from. This class inherits from JavaScript's `Error` class. This error object is rarely thrown alone, and usually a specialized error object with a specific meaning is thrown. It is recommended to use it to easily classify errors that have been caught using `try-catch` syntax if they are explicitly thrown by this SDK.

#### Properties

`.name: "SurrealError"`
:   The error name.

`.message`
:   The error message.

`.stack`
:   The stack trace may be recorded.

`.cause`
:   The cause or context of the error may be set.

### SurrealTypeError

Extends: `SurrealError`

This is an error thrown when input values or other validations fail.

#### Properties

`.name: "SurrealTypeError"`
:   The error name.

`.expected`
:   The expected data format.

`.actual`
:   A string representation of the actual value.

#### Solution

Trace the stack trace to find the cause of the unexpected data format.

### SurrealValueError

Extends: `SurrealError`

This is an error thrown when input values or other validations fail.

#### Properties

`.name: "SurrealValueError"`
:   The error name.

`.expected`
:   The expected data format.

`.actual`
:   The actual value.

#### Solution

Trace the stack trace to find the cause of the unexpected data format.

### SurrealAggregateError

Extends: `SurrealError`

This is an error that bundles multiple errors or error messages.

#### Properties

`.name: "SurrealAggregateError"`
:   The error name.

`.cause: unknown[]`
:   Each element of the array contains errors or error messages.

### CircularReferenceError

Extends: `SurrealError`

This is an error thrown when a circular reference is detected. This is mainly thrown during the process of converting JavaScript values to another format when the parent object detects the same object.

#### Properties

`.name: "CircularReferenceError"`
:   The error name.

For example, this error is thrown in the following case:

```ts
import { toSurql } from "@tai-kun/surrealdb/utils";

const a = {};
a.a = a;

console.log(a); // <ref *1> { a: [Circular *1] }

toSurql(a); // throws CircularReferenceError
```

#### Solution

This error can be thrown by other things besides the `toSurql` function. You need to carefully debug your object to see if it contains itself inside.

### NumberRangeError

Extends: `SurrealError`

This is an error thrown when a number takes a value outside the range.

#### Properties

`.name: "NumberRangeError"`
:   The error name.

`.range`
:   The expected range.

`.actual`
:   The actual value.

`.integer`
:   `true` if an integer is expected.

#### Solution

Trace the stack trace to find the cause of the unexpected data format.

### UnsupportedRuntimeError

Extends: `SurrealError`

This is an error thrown when an unsupported runtime is detected.

#### Properties

`.name: "UnsupportedRuntimeError"`
:   The error name.

#### Solution

You need to either not use the runtime, or use a polyfill and test it thoroughly.

### UnreachableError

Extends: `SurrealError`

This is an error thrown when an unreachable code is reached. If this error is thrown, you've likely encountered a bug in this SDK.

#### Properties

`.name: "UnreachableError"`
:   The error name.

#### Solution

You can raise this issue at the following URL:

[https://github.com/tai-kun/surrealdb.js/issues](https://github.com/tai-kun/surrealdb.js/issues)

## Client

### CircularEngineReferenceError

Extends: `CircularReferenceError`

This is an error thrown when a circular reference occurs between engines when connecting to a database.

#### Properties

`.name: "CircularEngineReferenceError"`
:   The error name.

`.seen: string[]`
:   A list of protocol names traversed before the circular reference occurred.

For example, this error is thrown in the following case:

```ts
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: "https",
    https: "http",
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws CircularEngineReferenceError: Circular engine reference: http,https
```

In the example above, the https protocol engine is set to use the engine configured for http, but the http protocol engine tries to use the engine configured for https, so a circular reference error is thrown.

#### Solution

Instead of setting the protocol name specified by a string to the value of another protocol name, replace it with a concrete implementation that creates an engine:

```ts del={6} ins={7-10}
import { initSurreal } from "@tai-kun/surrealdb";
import HttpEngine from "@tai-kun/surrealdb/engines/http";

const { Surreal } = initSurreal({
  engines: {
    http: "https",
    http: config => new HttpEngine({
      ...config,
      // fetch: <your custom fetch function>
    }),
    https: "http",
  },
  // ...
});
```

### EngineNotFoundError

Extends: `SurrealError`

This is an error thrown when trying to connect with a protocol for which an engine is not configured.

#### Properties

`.name: "EngineNotFoundError"`
:   The error name.

`.protocol: string`
:   The name of the protocol to connect to.

For example, this error is thrown in the following case:

```ts
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws EngineNotFoundError: No https protocol engine found.
```

#### Solution

Check the `engines` property to see if an engine can be created for the protocol of the endpoint you are connecting to.

```ts ins={6}
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
    https: "http",
  },
  // ...
});
```

### ConnectionConflictError

Extends: `SurrealError`

This is an error thrown when a client tries to connect to multiple endpoints simultaneously.

#### Properties

`.name: "ConnectionConflictError"`
:   The error name.

`.endpoint1: string`
:   One of the endpoints.

`.endpoint2: string`
:   The other endpoint.

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:11298"); // throws ConnectionConflictError: Connection conflict between http://localhost:8000/rpc and http://localhost:11298/rpc.
```

The `.connect` method appends `/rpc` to the URL passed to it if the path is not terminated with `/rpc`. Therefore, if the URL path of one of the endpoints ends with `/rpc`, the error may not occur even though it looks like it does:

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:8000/rpc"); // OK!
```

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000/rpc");
await db.connect("http://localhost:8000"); // OK!
```

#### Solution

You can connect to any endpoint by calling the `.close` method before calling the `.connect` method.

```ts ins={6}
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.close();
await db.connect("http://localhost:11298");
```

### MissingNamespaceError

Extends: `SurrealError`

This is an error thrown when a namespace is not selected before selecting a database. Or it is thrown if you try to make the namespace unselected while selecting a database.

#### Properties

`.name: "MissingNamespaceError"`
:   The error name.

`.database: string`
:   The database name.

For example, this error is thrown in the following case:

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({
  database: "example",
}); // throws MissingNamespaceError: The namespace must be specified before the database.
```

#### Solution

Make sure to select the namespace when selecting the database.

```ts ins={7}
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({
  namespace: "example",
  database: "example",
});
```

### RpcResponseError

Extends: `SurrealError`

This is an error thrown when the RPC response indicates an error. It does not mean there is a problem with the communication or decoding of the response body by the connected protocol, but it does mean that SurrealDB cannot process the RPC request.

#### Properties

`.name: "RpcResponseError"`
:   The error name.

`.id?: string`
:   The ID that identifies the RPC request. The ID always starts with `<method name>_`.

`.code: number`
:   While not explicitly documented in the SurrealDB documentation, it is likely to be a JSON-RPC error code.

#### Solution

There are many possible causes, but it is possible that the version of SurrelDB this SDK supports is different from the version of SurrealDB processing the RPC request.

### QueryFailedError

Extends: `SurrealAggregateError`

This is an error thrown when a query fails.

#### Properties

`.name: "QueryFailedError"`
:   The error name.

`.cause: string[]`
:   A list of errors.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.query("OUTPUT 'Hello'"); // throws QueryFailedError: Query failed with 1 error(s)
```

#### Solution

Check the SurrelQL syntax for correctness.

### Closed

Extends: `SurrealError`

This error indicates that the connection was forcibly terminated.

#### Properties

`.name: "Closed"`
:   The error name.

For example, you get this error in the following case:

```ts
const db = new Surreal();

db.on("<event_name>", ({ signal }) => {
  return new Promise((resolve, reject) => {
    signal.addEventListener("abort", function() {
      console.error(this.reason); // Closed
      reject();
    })

    // ...
  });
});

await db.close({ force: true });
```

## Engine

### EngineError

Extends: `SurrealError`

This indicates that the error is due to the engine. It is sent via an event listener.

#### Properties

`.name: "EngineError"`
:   The error name.

`.fatal: boolean | undefined`
:   Indicates whether this error is fatal.

### HttpEngineError

Extends: `EngineError`

This indicates that the error is due to the HTTP engine. This is currently just defined and not used.

#### Properties

`.name: "HttpEngineError"`
:   The error name.

### WebSocketEngineError

Extends: `EngineError`

This indicates that the error is due to the WebSocket engine. It is used when the response body cannot be parsed before finding the ID that identifies the RPC request, when an error event is received from the WebSocket object, or when the WebSocket connection is closed.

This SDK uses `315x` as a custom status code. This range is unassigned in the [IANA](https://www.iana.org/assignments/websocket/websocket.xml#close-code-number).

#### Properties

`.name: "WebSocketEngineError"`
:   The error name.

`.code: number`
:   One of the following status codes:
    - `1000`~`1015`: [MDN Reference](https://developer.mozilla.org/docs/Web/API/CloseEvent/code)
    - `3150`: Indicates that an "error" event was received from the `WebSocket`[^1] instance.
    - `3151`: Indicates that an error occurred in the "open" event handler registered by the WebSocket engine. It is often the case that `StateTransitionError` is thrown during the transition from the connecting state to the connected state.
    - `3152`: Indicates that an error occurred in the "message" event handler registered by the WebSocket engine. There are many possible causes, but the most likely is that `ServerResponseError` or `RpcResponseError` was thrown in the event handler. It is likely caused by a request with invalid RPC parameters. In that case, the method that calls the RPC (by default) times out after 5 seconds and fails. In versions before SurrealDB v2.0.2, timeouts could be caused by a wider range of reasons.
    - `3153`: Indicates that the ping failed to be sent or received. This could be a temporary error, but if you keep receiving it, you may not be able to maintain the connection.
    - `3154`: Indicates that an error occurred in the "close" event handler registered by the WebSocket engine. It is often the case that `StateTransitionError` is thrown during the transition from the disconnecting state to the disconnected state.
:   Note the following status codes are excluded from the above. This SDK does not treat them as errors.
    - `1000`: Disconnected normally.
    - `1001`: Early disconnection is common.
    - `1004`: Reserved.
    - `1005`: Reserved.
    - `1006`: Reserved.
    - `1015`: Reserved.

^1: `WebSocket` is the class defined by the runtime in the global variable or the class of `ws`.

#### Solution

`1002`,`1003`,`1007`...`1011`,`1014`,`3150`,`3151`,`3154`
:   There is probably no way to recover automatically from this status code. You will need to fix the runtime, SurrealDB settings, or hard-coded implementation.

`3152`
:   Check if the arguments passed to the method (i.e. the contents of the RPC request) are correct.

`1012`,`1013`,`3153`
:   You may be able to recover automatically using the experimental feature [`autoReconnect()`](/v2/experimental/auto-reconnect).

### StateTransitionError

Extends: `SurrealAggregateError`

This is an error thrown when an event listener fails to execute during a state transition.

#### Properties

`.name: "StateTransitionError"`
:   The error name.

`.from: string`
:   The state at the beginning of the state transition.

`.to: string`
:   The state to transition to.

`.fallback: string`
:   The alternative transition destination if the state transition fails. If it is the same value as `.to`, it means that the transition was forced.

For example, this error is thrown in the following case:

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

db.on("connecting", () => {
  throw new Error("Don't let me connect !!!")
});

await db.connect("http://localhost:8000"); // throws ...
// StateTransitionError: The transition from `3` to `0` failed, falling back to `3`.
//     at <stack trace ...> {
//   cause: [
//     Error: Don't let me connect !!!
//         at <stack trace ...>
//   ],
//   from: 3,
//   to: 0,
//   fallback: 3
// }
```

### ConnectionUnavailableError

Extends: `SurrealError`

This is an error thrown when you try to send an RPC request in a disconnected state.

#### Properties

`.name: "ConnectionUnavailableError"`
:   The error name.

### ServerResponseError

Extends: `SurrealError`

This is an error thrown when the response cannot be parsed as a PRC response. This is different from `RpcResponseError`.

#### Properties

`.name: "ServerResponseError"`
:   The error name.

#### Solution

Normally this error should never be thrown, but if it is thrown, it is possible that the version of SurrelDB this SDK supports is different from the version of SurrealDB processing the RPC request.

## CBOR

### CborError

Extends: `SurrealError`

This is the class that all errors related to CBOR that are explicitly thrown by `@tai-kun/surrealdb/cbor` inherit from. This is never thrown directly.

#### Properties

`.name: "CborError"`
:   The error name.

### CborWellFormednessError

Extends: `CborError`

#### Properties

This is the class that all errors related to CBOR decoding that are explicitly thrown by `@tai-kun/surrealdb/cbor` inherit from. This is never thrown directly.

Refer to "[Well-Formedness Errors and Examples](https://datatracker.ietf.org/doc/html/rfc8949#name-well-formedness-errors-and-)" in Appendix F of RFC8949.

`.name: "CborWellFormednessError"`
:   The error name.

### CborTooMuchDataError

Extends: `CborWellFormednessError`

This indicates that there are unconsumed input bytes remaining.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.2)

#### Properties

`.name: "CborTooMuchDataError"`
:   The error name.

#### Solution

Check if the byte array to be decoded is in the correct CBOR format.

### CborTooLittleDataError

Extends: `CborWellFormednessError`

This indicates that the input bytes are incomplete.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.4)

#### Properties

`.name: "CborTooLittleDataError"`
:   The error name.

#### Solution

Check if the byte array to be decoded is in the correct CBOR format.

### CborSyntaxError

Extends: `CborWellFormednessError`

Indicates that the input bytes do not match the CBOR encoding format.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.6)

#### Properties

`.name: "CborSyntaxError"`
:   The error name.

#### Solution

Check if the byte array to be decoded is in the correct CBOR format.

### CborMaxDepthReachedError

Extends: `CborError`

This error is thrown when the depth of the JavaScript object reaches the maximum value during CBOR encoding or decoding. The depth increases by 1 for every object or array entered.

#### Properties

`.name: "CborMaxDepthReachedError"`
:   The error name.

`.maxDepth: number`
:   The maximum depth.

#### Solution

Relax the upper limit of the optional `.maxDepth` or review the data structure so that the object nesting is shallow.

```ts
import CborFormatter from "@tai-kun/surrealdb/formatters/cbor";

const cborFormatter = new CborFormatter({
  encode: {
    maxDepth: 1024,
  },
  decode: {
    maxDepth: 1024,
  },
  // ...
})
```

### CborUnsafeMapKeyError

Extends: `CborError`

This error is thrown when an unsafe map key is found during CBOR encoding or decoding.

#### Properties

`.name: "CborUnsafeMapKeyError"`
:   The error name.

`.key: unknown`
:   The map key that was determined to be unsafe.

## JSON

### JsonError

Extends: `SurrealError`

This is the class that all errors related to JSON that are explicitly thrown by `@tai-kun/surrealdb/formatters/json` inherit from. This is never thrown directly.

#### Properties

`.name: "JsonError"`
:   The error name.

### JsonUnsafeMapKeyError

Extends: `JsonError`

This error is thrown when an unsafe map key is found during JSON decoding.

#### Properties

`.name: "JsonUnsafeMapKeyError"`
:   The error name.

`.key: unknown`
:   The map key that was determined to be unsafe.
